### ISSUE TITLE
Disable _R_CHECK_DOC_SIZES_

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-backend#13]
You either need to set `_R_CHECK_DOC_SIZES_=0` or install `qpdf` on all platforms. Honestly I think this might be the most useless check of them all, might as well just disable it everywhere.

<img width="532" alt="screen shot 2016-10-21 at 3 35 03 pm" src="https://cloud.githubusercontent.com/assets/216319/19600185/2b13eeb8-97a4-11e6-9eae-0eca594fc929.png">

**Comment by gaborcsardi** [comment]
Do you know if `--as-cran` turns these back on? Or the environment variables are still used with `--as-cran`?

**Comment by jeroen** [comment]
I think the variables take precedence. I often combine `FORCE_CHECK_SUGGESTS` with `--as-cran` and that seems to work.

**Comment by gaborcsardi** [comment]
I think I'll install `qpdf`, because I want to make `check_for_cran()` to be close to the CRAN checks.....

**Comment by gaborcsardi** [comment]
Need to rebuild all images for the recent Linux bug, anyway....

**Comment by gaborcsardi** [comment]
All images should have qpdf now I believe.
