### ISSUE TITLE
Timeout during package install on Windows

### ISSUE THREAD

**Issue by rubak** [r-hub/rhub-backend#20]
I hope this is the correct repo to report this. I don't have a complete overview of the various r-hub repos.

When testing package `spatstat` using R-hub platform `windows-x86_64-devel` the job aborts during package install as can be seen [here][1]. It doesn't happen on platform `debial-gcc-devel`. Could the time limit be increased or is there some other way around this?

[1]: https://builder.r-hub.io/status/spatstat_1.50-0.tar.gz-1fce39301ee945a297abb1c84cfa6abd#L380

**Comment by gaborcsardi** [comment]
I think this is an error in R, or with the binary packages possibly. It stops at
```
 379#> ** byte-compile and prepare package for lazy loading
 380#> Build timed out (after 10 minutes). Marking the build as aborted.
 381#> Build was aborted
```
and imo it is highly unlikely that the byte-compiling takes more than 10 minutes.

**Comment by gaborcsardi** [comment]
Try adding 
```
ByteCompile: no
```
in `DESCRIPTION`, to avoid byte compiling the package.

**Comment by rubak** [comment]
OK. Trying that now.

**Comment by rubak** [comment]
It timed out again in the same place (now just preparing LazyLoad) as seen [here][1].
It doesn't happen under R-release as seen [here][2].
However @baddstats submitted to win-builder earlier today and it installed fine under R-devel as seen [here][3], so R-devel is not completely incapable of installing `spatstat`. (However, it failed an example due to problems with `fftwtools` which was why I wanted to test on r-hub in the first place.)
Related to that I now found out that `fftwtools` can't be installed from source on Windows on R-hub due to the system requirement `fftw3` which isn't available, so I guess there is no way to test with a development version of something that has system requirements like this on Windows?
(I have the said development version in a fork at https://github.com/rubak/fftwtools and I put that in the `Remotes:` field of `DESCRIPTION`, and it correctly tries to install it but then fails.)

[1]: https://builder.r-hub.io/status/spatstat_1.50-0.tar.gz-c65ce451a237477abbdbfc02c8c8bd87#L380
[2]: https://builder.r-hub.io/status/spatstat_1.50-0.tar.gz-7eaaf30c0bd44dd1bce2262923f34d2e#L383
[3]: https://win-builder.r-project.org/incoming_pretest/170322_054957_spatstat_1500/00check.log

**Comment by gaborcsardi** [comment]
Seems like this is not an issue any more.
