### ISSUE TITLE
Support _R_FORCE_CHECK_SUGGESTS_

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-backend#8]
Currently we cannot check packages that have an unavailable `Suggests` dependency (e.g a windows-only package). Setting `_R_FORCE_CHECK_SUGGESTS_=false` will turn this into a NOTE instead of ERROR (unless of course the suggest is actually required for checking).

So we either need a way to enable enable this, or make it the default.

**Comment by gaborcsardi** [comment]
Are you sure that it is set to `false` for CRAN checks?

**Comment by jeroen** [comment]
Yes, otherwise all packages that suggest some sort of platform specific package would fail check.

**Comment by jeroen** [comment]
Or perhaps they set it on a per-package basis, but I think it is the default actually.

**Comment by jeroen** [comment]
See for example opencpu checks: https://cran.r-project.org/web/checks/check_results_opencpu.html

OpenCPU suggests RAppArmor (which is only available on Debian).

**Comment by gaborcsardi** [comment]
OK, I'll set it to `false` then.

**Comment by gaborcsardi** [comment]
Also deployed.
